package com.app.Components;

import com.app.dbIO.DBConnection;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.sqlcontainer.query.TableQuery;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class Veranstaltung extends CustomComponent {

	private ComboBox veranstaltungsAuswahl;
	private Button neueVeranstaltung;
	private ComboBox veranstaltungsTypFuerNeu;

	private TextField nameVeranstaltung;
	private TextField nameRichter;
	private TextField nameVeranstaltungsLeiter;
	private TextField veranstalter;
	private TextField veranstaltungsOrt;
	private PopupDateField datumVeranstaltung;
	
	private Item currentVeranstaltung;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Veranstaltung() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		

		TableQuery q1 = new TableQuery("veranstaltung",
				DBConnection.INSTANCE.getConnectionPool());
		q1.setVersionColumn("version");
		

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();

		mainLayout.setWidth("1000px");
		mainLayout.setHeight(null);
		mainLayout.setImmediate(false);
		// mainLayout.setMargin(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		Accordion x = new Accordion();
		x.setSizeFull();

		x.addTab(createSecondPanel(), "Allgemein", null);
		x.addTab(createThirdPanel(), "Anmeldungen + Bewertungen", null);

		mainLayout.addComponent(createFirstPanel());
		mainLayout.addComponent(x);

		return mainLayout;
	}

	private Panel createFirstPanel() {
		Panel firstLinePanel = new Panel();
		GridLayout firstLinePanelLayout = new GridLayout(3, 1);
		firstLinePanelLayout.setWidth("50%");
		firstLinePanelLayout.setHeight("50%");

		veranstaltungsAuswahl = new ComboBox();
		veranstaltungsAuswahl.setImmediate(true);
		veranstaltungsAuswahl.addItem("1");

		firstLinePanelLayout.addComponent(veranstaltungsAuswahl, 0, 0);

		neueVeranstaltung = new Button();
		neueVeranstaltung.setCaption("neue Veranstaltung");
		neueVeranstaltung.setImmediate(true);
		neueVeranstaltung.setHeight("-1px");
		neueVeranstaltung.setWidth("-1px");

		firstLinePanelLayout.addComponent(neueVeranstaltung, 1, 0);

		veranstaltungsTypFuerNeu = new ComboBox();
		veranstaltungsTypFuerNeu.setImmediate(true);
		veranstaltungsTypFuerNeu.addItem("2");

		firstLinePanelLayout.addComponent(veranstaltungsTypFuerNeu, 2, 0);

		firstLinePanel.setContent(firstLinePanelLayout);

		return firstLinePanel;
	}

	private Panel createSecondPanel() {
		Panel secondLine = new Panel();

		HorizontalLayout secondLineLayout = new HorizontalLayout();
		secondLineLayout.setWidth("100%");
		secondLineLayout.setHeight("100%");

		nameVeranstaltung = new TextField("Veranstaltungsname");
		nameVeranstaltung.setImmediate(true);
		nameVeranstaltung.setWidth("-1px");
		nameVeranstaltung.setHeight("-1px");
		nameVeranstaltung.setMaxLength(45);
		secondLineLayout.addComponent(nameVeranstaltung);

		nameVeranstaltungsLeiter = new TextField(
				"Veranstaltungs-/Prüfungsleiter");
		nameVeranstaltungsLeiter.setImmediate(true);
		nameVeranstaltungsLeiter.setWidth("-1px");
		nameVeranstaltungsLeiter.setHeight("-1px");
		nameVeranstaltungsLeiter.setMaxLength(45);
		secondLineLayout.addComponent(nameVeranstaltungsLeiter);

		datumVeranstaltung = new PopupDateField("Datum der Veranstaltung");
		datumVeranstaltung.setImmediate(true);
		datumVeranstaltung.setWidth("-1px");
		datumVeranstaltung.setHeight("-1px");
		secondLineLayout.addComponent(datumVeranstaltung);

		nameRichter = new TextField("Name Richter");
		nameRichter.setImmediate(true);
		nameRichter.setWidth("-1px");
		nameRichter.setHeight("-1px");
		nameRichter.setMaxLength(45);
		secondLineLayout.addComponent(nameRichter);

		veranstalter = new TextField("Veranstalter");
		veranstalter.setImmediate(true);
		veranstalter.setWidth("-1px");
		veranstalter.setHeight("-1px");
		veranstalter.setMaxLength(45);
		secondLineLayout.addComponent(veranstalter);

		veranstaltungsOrt = new TextField("Veranstaltungsort");
		veranstaltungsOrt.setImmediate(true);
		veranstaltungsOrt.setWidth("-1px");
		veranstaltungsOrt.setHeight("-1px");
		veranstaltungsOrt.setMaxLength(45);
		secondLineLayout.addComponent(veranstaltungsOrt);
		
		secondLine.setContent(secondLineLayout);
	
	
	

		return secondLine;
	}

	private Panel createThirdPanel() {
		Panel thirdLine = new Panel();

		return thirdLine;
	}
}
