package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * ausstellungscup_komprimiert generated by hbm2java
 */
public class ausstellungscup_komprimiert implements java.io.Serializable {

	private int idausstellungscupKomprimiert;
	private int version;
	private int oercid;
	private String showjahr;
	private int punkte;
	private String zuWertenIn;
	private int gespunkte;

	public ausstellungscup_komprimiert() {
	}

	public ausstellungscup_komprimiert(int oercid, String showjahr, int punkte, String zuWertenIn, int gespunkte) {
		this.oercid = oercid;
		this.showjahr = showjahr;
		this.punkte = punkte;
		this.zuWertenIn = zuWertenIn;
		this.gespunkte = gespunkte;
	}

	public int getIdausstellungscupKomprimiert() {
		return this.idausstellungscupKomprimiert;
	}

	public void setIdausstellungscupKomprimiert(int idausstellungscupKomprimiert) {
		this.idausstellungscupKomprimiert = idausstellungscupKomprimiert;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getOercid() {
		return this.oercid;
	}

	public void setOercid(int oercid) {
		this.oercid = oercid;
	}

	public String getShowjahr() {
		return this.showjahr;
	}

	public void setShowjahr(String showjahr) {
		this.showjahr = showjahr;
	}

	public int getPunkte() {
		return this.punkte;
	}

	public void setPunkte(int punkte) {
		this.punkte = punkte;
	}

	public String getZuWertenIn() {
		return this.zuWertenIn;
	}

	public void setZuWertenIn(String zuWertenIn) {
		this.zuWertenIn = zuWertenIn;
	}

	public int getGespunkte() {
		return this.gespunkte;
	}

	public void setGespunkte(int gespunkte) {
		this.gespunkte = gespunkte;
	}

}
