package com.app.entitites;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * ausstellungscup_basis generated by hbm2java
 */
@Entity
@Table(name="ausstellungscup_basis")
public class AusstellungsCupBasis implements java.io.Serializable {

	private int ausstellungscupBasisId;
	private int version;
	private int idschau;
	private int idschauhund;
	private Integer oercid;
	private int punkte;
	private String ausklasse;
	private String showjahr;
	private String zbnrFilterValue;
	private Character streichergebnis;

	public AusstellungsCupBasis() {
	}

	public AusstellungsCupBasis(int idschau, int idschauhund, int punkte, String ausklasse, String showjahr,
			String zbnrFilterValue) {
		this.idschau = idschau;
		this.idschauhund = idschauhund;
		this.punkte = punkte;
		this.ausklasse = ausklasse;
		this.showjahr = showjahr;
		this.zbnrFilterValue = zbnrFilterValue;
	}

	public AusstellungsCupBasis(int idschau, int idschauhund, Integer oercid, int punkte, String ausklasse,
			String showjahr, String zbnrFilterValue, Character streichergebnis) {
		this.idschau = idschau;
		this.idschauhund = idschauhund;
		this.oercid = oercid;
		this.punkte = punkte;
		this.ausklasse = ausklasse;
		this.showjahr = showjahr;
		this.zbnrFilterValue = zbnrFilterValue;
		this.streichergebnis = streichergebnis;
	}

	public int getAusstellungscupBasisId() {
		return this.ausstellungscupBasisId;
	}

	public void setAusstellungscupBasisId(int ausstellungscupBasisId) {
		this.ausstellungscupBasisId = ausstellungscupBasisId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getIdschau() {
		return this.idschau;
	}

	public void setIdschau(int idschau) {
		this.idschau = idschau;
	}

	public int getIdschauhund() {
		return this.idschauhund;
	}

	public void setIdschauhund(int idschauhund) {
		this.idschauhund = idschauhund;
	}

	public Integer getOercid() {
		return this.oercid;
	}

	public void setOercid(Integer oercid) {
		this.oercid = oercid;
	}

	public int getPunkte() {
		return this.punkte;
	}

	public void setPunkte(int punkte) {
		this.punkte = punkte;
	}

	public String getAusklasse() {
		return this.ausklasse;
	}

	public void setAusklasse(String ausklasse) {
		this.ausklasse = ausklasse;
	}

	public String getShowjahr() {
		return this.showjahr;
	}

	public void setShowjahr(String showjahr) {
		this.showjahr = showjahr;
	}

	public String getZbnrFilterValue() {
		return this.zbnrFilterValue;
	}

	public void setZbnrFilterValue(String zbnrFilterValue) {
		this.zbnrFilterValue = zbnrFilterValue;
	}

	public Character getStreichergebnis() {
		return this.streichergebnis;
	}

	public void setStreichergebnis(Character streichergebnis) {
		this.streichergebnis = streichergebnis;
	}

}
