package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * auswertungsbasis generated by hbm2java
 */
public class auswertungsbasis implements java.io.Serializable {

	private String name;

	public auswertungsbasis() {
	}

	public auswertungsbasis(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
