package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * ellenbogen generated by hbm2java
 */
public class ellenbogen implements java.io.Serializable {

	private int id;
	private String name;
	private String oberkategorie;
	private String unterkategorie;
	private String merkmal;
	private String wert;
	private String datum;
	private String bemerkung;
	private String quelle;
	private String status;

	public ellenbogen() {
	}

	public ellenbogen(int id, String name, String oberkategorie, String unterkategorie, String merkmal, String status) {
		this.id = id;
		this.name = name;
		this.oberkategorie = oberkategorie;
		this.unterkategorie = unterkategorie;
		this.merkmal = merkmal;
		this.status = status;
	}

	public ellenbogen(int id, String name, String oberkategorie, String unterkategorie, String merkmal, String wert,
			String datum, String bemerkung, String quelle, String status) {
		this.id = id;
		this.name = name;
		this.oberkategorie = oberkategorie;
		this.unterkategorie = unterkategorie;
		this.merkmal = merkmal;
		this.wert = wert;
		this.datum = datum;
		this.bemerkung = bemerkung;
		this.quelle = quelle;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOberkategorie() {
		return this.oberkategorie;
	}

	public void setOberkategorie(String oberkategorie) {
		this.oberkategorie = oberkategorie;
	}

	public String getUnterkategorie() {
		return this.unterkategorie;
	}

	public void setUnterkategorie(String unterkategorie) {
		this.unterkategorie = unterkategorie;
	}

	public String getMerkmal() {
		return this.merkmal;
	}

	public void setMerkmal(String merkmal) {
		this.merkmal = merkmal;
	}

	public String getWert() {
		return this.wert;
	}

	public void setWert(String wert) {
		this.wert = wert;
	}

	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	public String getQuelle() {
		return this.quelle;
	}

	public void setQuelle(String quelle) {
		this.quelle = quelle;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
