package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * elternupdateId generated by hbm2java
 */
public class elternupdateId implements java.io.Serializable {

	private String hundename;
	private String zuchtbuchnummer;
	private String chipnummer;
	private String vater;
	private String mutter;

	public elternupdateId() {
	}

	public elternupdateId(String hundename, String zuchtbuchnummer, String chipnummer, String vater, String mutter) {
		this.hundename = hundename;
		this.zuchtbuchnummer = zuchtbuchnummer;
		this.chipnummer = chipnummer;
		this.vater = vater;
		this.mutter = mutter;
	}

	public String getHundename() {
		return this.hundename;
	}

	public void setHundename(String hundename) {
		this.hundename = hundename;
	}

	public String getZuchtbuchnummer() {
		return this.zuchtbuchnummer;
	}

	public void setZuchtbuchnummer(String zuchtbuchnummer) {
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

	public String getChipnummer() {
		return this.chipnummer;
	}

	public void setChipnummer(String chipnummer) {
		this.chipnummer = chipnummer;
	}

	public String getVater() {
		return this.vater;
	}

	public void setVater(String vater) {
		this.vater = vater;
	}

	public String getMutter() {
		return this.mutter;
	}

	public void setMutter(String mutter) {
		this.mutter = mutter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof elternupdateId))
			return false;
		elternupdateId castOther = (elternupdateId) other;

		return ((this.getHundename() == castOther.getHundename()) || (this.getHundename() != null
				&& castOther.getHundename() != null && this.getHundename().equals(castOther.getHundename())))
				&& ((this.getZuchtbuchnummer() == castOther.getZuchtbuchnummer())
						|| (this.getZuchtbuchnummer() != null && castOther.getZuchtbuchnummer() != null
								&& this.getZuchtbuchnummer().equals(castOther.getZuchtbuchnummer())))
				&& ((this.getChipnummer() == castOther.getChipnummer()) || (this.getChipnummer() != null
						&& castOther.getChipnummer() != null && this.getChipnummer().equals(castOther.getChipnummer())))
				&& ((this.getVater() == castOther.getVater()) || (this.getVater() != null
						&& castOther.getVater() != null && this.getVater().equals(castOther.getVater())))
				&& ((this.getMutter() == castOther.getMutter()) || (this.getMutter() != null
						&& castOther.getMutter() != null && this.getMutter().equals(castOther.getMutter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHundename() == null ? 0 : this.getHundename().hashCode());
		result = 37 * result + (getZuchtbuchnummer() == null ? 0 : this.getZuchtbuchnummer().hashCode());
		result = 37 * result + (getChipnummer() == null ? 0 : this.getChipnummer().hashCode());
		result = 37 * result + (getVater() == null ? 0 : this.getVater().hashCode());
		result = 37 * result + (getMutter() == null ? 0 : this.getMutter().hashCode());
		return result;
	}

}
