package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * elternupdate generated by hbm2java
 */
public class elternupdate implements java.io.Serializable {

	private elternupdateId id;

	public elternupdate() {
	}

	public elternupdate(elternupdateId id) {
		this.id = id;
	}

	public elternupdateId getId() {
		return this.id;
	}

	public void setId(elternupdateId id) {
		this.id = id;
	}

}
