package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * email generated by hbm2java
 */
public class email implements java.io.Serializable {

	private int emailid;
	private int version;
	private String an;
	private String bc;
	private String bcc;
	private String betreff;
	private String inhalt;
	private String attachement;

	public email() {
	}

	public email(int emailid) {
		this.emailid = emailid;
	}

	public email(int emailid, String an, String bc, String bcc, String betreff, String inhalt, String attachement) {
		this.emailid = emailid;
		this.an = an;
		this.bc = bc;
		this.bcc = bcc;
		this.betreff = betreff;
		this.inhalt = inhalt;
		this.attachement = attachement;
	}

	public int getEmailid() {
		return this.emailid;
	}

	public void setEmailid(int emailid) {
		this.emailid = emailid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getAn() {
		return this.an;
	}

	public void setAn(String an) {
		this.an = an;
	}

	public String getBc() {
		return this.bc;
	}

	public void setBc(String bc) {
		this.bc = bc;
	}

	public String getBcc() {
		return this.bcc;
	}

	public void setBcc(String bcc) {
		this.bcc = bcc;
	}

	public String getBetreff() {
		return this.betreff;
	}

	public void setBetreff(String betreff) {
		this.betreff = betreff;
	}

	public String getInhalt() {
		return this.inhalt;
	}

	public void setInhalt(String inhalt) {
		this.inhalt = inhalt;
	}

	public String getAttachement() {
		return this.attachement;
	}

	public void setAttachement(String attachement) {
		this.attachement = attachement;
	}

}
