package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * emailattachment generated by hbm2java
 */
public class emailattachment implements java.io.Serializable {

	private int attachmentid;
	private int version;
	private String filename;
	private String datei;
	private int emailid;

	public emailattachment() {
	}

	public emailattachment(int attachmentid, int emailid) {
		this.attachmentid = attachmentid;
		this.emailid = emailid;
	}

	public emailattachment(int attachmentid, String filename, String datei, int emailid) {
		this.attachmentid = attachmentid;
		this.filename = filename;
		this.datei = datei;
		this.emailid = emailid;
	}

	public int getAttachmentid() {
		return this.attachmentid;
	}

	public void setAttachmentid(int attachmentid) {
		this.attachmentid = attachmentid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getDatei() {
		return this.datei;
	}

	public void setDatei(String datei) {
		this.datei = datei;
	}

	public int getEmailid() {
		return this.emailid;
	}

	public void setEmailid(int emailid) {
		this.emailid = emailid;
	}

}
