package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * hund generated by hbm2java
 */
public class hund implements java.io.Serializable {

	private int idhund;
	private int version;
	private Integer idperson;
	private String zwingername;
	private String rufname;
	private Date wurfdatum;
	private String rasse;
	private Date bhdatum;
	private String zuchtbuchnummer;
	private String chipnummer;
	private String vater;
	private Integer vaterIdhund;
	private String mutter;
	private Integer mutterIdhund;
	private String zuechter;
	private String farbe;
	private char geschlecht;
	private Integer hundenr;

	public hund() {
	}

	public hund(String rufname, String rasse, String chipnummer, char geschlecht) {
		this.rufname = rufname;
		this.rasse = rasse;
		this.chipnummer = chipnummer;
		this.geschlecht = geschlecht;
	}

	public hund(Integer idperson, String zwingername, String rufname, Date wurfdatum, String rasse, Date bhdatum,
			String zuchtbuchnummer, String chipnummer, String vater, Integer vaterIdhund, String mutter,
			Integer mutterIdhund, String zuechter, String farbe, char geschlecht, Integer hundenr) {
		this.idperson = idperson;
		this.zwingername = zwingername;
		this.rufname = rufname;
		this.wurfdatum = wurfdatum;
		this.rasse = rasse;
		this.bhdatum = bhdatum;
		this.zuchtbuchnummer = zuchtbuchnummer;
		this.chipnummer = chipnummer;
		this.vater = vater;
		this.vaterIdhund = vaterIdhund;
		this.mutter = mutter;
		this.mutterIdhund = mutterIdhund;
		this.zuechter = zuechter;
		this.farbe = farbe;
		this.geschlecht = geschlecht;
		this.hundenr = hundenr;
	}

	public int getIdhund() {
		return this.idhund;
	}

	public void setIdhund(int idhund) {
		this.idhund = idhund;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Integer getIdperson() {
		return this.idperson;
	}

	public void setIdperson(Integer idperson) {
		this.idperson = idperson;
	}

	public String getZwingername() {
		return this.zwingername;
	}

	public void setZwingername(String zwingername) {
		this.zwingername = zwingername;
	}

	public String getRufname() {
		return this.rufname;
	}

	public void setRufname(String rufname) {
		this.rufname = rufname;
	}

	public Date getWurfdatum() {
		return this.wurfdatum;
	}

	public void setWurfdatum(Date wurfdatum) {
		this.wurfdatum = wurfdatum;
	}

	public String getRasse() {
		return this.rasse;
	}

	public void setRasse(String rasse) {
		this.rasse = rasse;
	}

	public Date getBhdatum() {
		return this.bhdatum;
	}

	public void setBhdatum(Date bhdatum) {
		this.bhdatum = bhdatum;
	}

	public String getZuchtbuchnummer() {
		return this.zuchtbuchnummer;
	}

	public void setZuchtbuchnummer(String zuchtbuchnummer) {
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

	public String getChipnummer() {
		return this.chipnummer;
	}

	public void setChipnummer(String chipnummer) {
		this.chipnummer = chipnummer;
	}

	public String getVater() {
		return this.vater;
	}

	public void setVater(String vater) {
		this.vater = vater;
	}

	public Integer getVaterIdhund() {
		return this.vaterIdhund;
	}

	public void setVaterIdhund(Integer vaterIdhund) {
		this.vaterIdhund = vaterIdhund;
	}

	public String getMutter() {
		return this.mutter;
	}

	public void setMutter(String mutter) {
		this.mutter = mutter;
	}

	public Integer getMutterIdhund() {
		return this.mutterIdhund;
	}

	public void setMutterIdhund(Integer mutterIdhund) {
		this.mutterIdhund = mutterIdhund;
	}

	public String getZuechter() {
		return this.zuechter;
	}

	public void setZuechter(String zuechter) {
		this.zuechter = zuechter;
	}

	public String getFarbe() {
		return this.farbe;
	}

	public void setFarbe(String farbe) {
		this.farbe = farbe;
	}

	public char getGeschlecht() {
		return this.geschlecht;
	}

	public void setGeschlecht(char geschlecht) {
		this.geschlecht = geschlecht;
	}

	public Integer getHundenr() {
		return this.hundenr;
	}

	public void setHundenr(Integer hundenr) {
		this.hundenr = hundenr;
	}

}
