package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * iha_grunddaten generated by hbm2java
 */
public class iha_grunddaten implements java.io.Serializable {

	private iha_grunddatenId id;

	public iha_grunddaten() {
	}

	public iha_grunddaten(iha_grunddatenId id) {
		this.id = id;
	}

	public iha_grunddatenId getId() {
		return this.id;
	}

	public void setId(iha_grunddatenId id) {
		this.id = id;
	}

}
