package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * importId generated by hbm2java
 */
public class ImportId implements java.io.Serializable {

	private String ausstellungstag;
	private int katalognummer;

	public ImportId() {
	}

	public ImportId(String ausstellungstag, int katalognummer) {
		this.ausstellungstag = ausstellungstag;
		this.katalognummer = katalognummer;
	}

	public String getAusstellungstag() {
		return this.ausstellungstag;
	}

	public void setAusstellungstag(String ausstellungstag) {
		this.ausstellungstag = ausstellungstag;
	}

	public int getKatalognummer() {
		return this.katalognummer;
	}

	public void setKatalognummer(int katalognummer) {
		this.katalognummer = katalognummer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportId))
			return false;
		ImportId castOther = (ImportId) other;

		return ((this.getAusstellungstag() == castOther.getAusstellungstag())
				|| (this.getAusstellungstag() != null && castOther.getAusstellungstag() != null
						&& this.getAusstellungstag().equals(castOther.getAusstellungstag())))
				&& (this.getKatalognummer() == castOther.getKatalognummer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAusstellungstag() == null ? 0 : this.getAusstellungstag().hashCode());
		result = 37 * result + this.getKatalognummer();
		return result;
	}

}
