package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * Kurskartenbesuche generated by hbm2java
 */
public class Kurskartenbesuche implements java.io.Serializable {

	private int idkurskartenbesuche;
	private int idkurskarte;
	private Date besuch;

	public Kurskartenbesuche() {
	}

	public Kurskartenbesuche(int idkurskarte, Date besuch) {
		this.idkurskarte = idkurskarte;
		this.besuch = besuch;
	}

	public int getIdkurskartenbesuche() {
		return this.idkurskartenbesuche;
	}

	public void setIdkurskartenbesuche(int idkurskartenbesuche) {
		this.idkurskartenbesuche = idkurskartenbesuche;
	}

	public int getIdkurskarte() {
		return this.idkurskarte;
	}

	public void setIdkurskarte(int idkurskarte) {
		this.idkurskarte = idkurskarte;
	}

	public Date getBesuch() {
		return this.besuch;
	}

	public void setBesuch(Date besuch) {
		this.besuch = besuch;
	}

}
