package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * kursstunde generated by hbm2java
 */
public class kursstunde implements java.io.Serializable {

	private int idkursstunde;
	private int version;
	private String bezeichnung;
	private int idkurstag;
	private Date startzeit;
	private Date endzeit;

	public kursstunde() {
	}

	public kursstunde(String bezeichnung, int idkurstag, Date startzeit, Date endzeit) {
		this.bezeichnung = bezeichnung;
		this.idkurstag = idkurstag;
		this.startzeit = startzeit;
		this.endzeit = endzeit;
	}

	public int getIdkursstunde() {
		return this.idkursstunde;
	}

	public void setIdkursstunde(int idkursstunde) {
		this.idkursstunde = idkursstunde;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public int getIdkurstag() {
		return this.idkurstag;
	}

	public void setIdkurstag(int idkurstag) {
		this.idkurstag = idkurstag;
	}

	public Date getStartzeit() {
		return this.startzeit;
	}

	public void setStartzeit(Date startzeit) {
		this.startzeit = startzeit;
	}

	public Date getEndzeit() {
		return this.endzeit;
	}

	public void setEndzeit(Date endzeit) {
		this.endzeit = endzeit;
	}

}
