package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * kurs generated by hbm2java
 */
public class kurs implements java.io.Serializable {

	private int idkurs;
	private int version;
	private String kursbezeichnung;
	private Date startdat;
	private Date endedat;
	private BigDecimal oerc1Hund;
	private BigDecimal oerc2Hund;
	private BigDecimal noerc1Hund;
	private BigDecimal noerc2Hund;

	public kurs() {
	}

	public kurs(String kursbezeichnung, Date startdat, Date endedat, BigDecimal oerc1Hund, BigDecimal oerc2Hund,
			BigDecimal noerc1Hund, BigDecimal noerc2Hund) {
		this.kursbezeichnung = kursbezeichnung;
		this.startdat = startdat;
		this.endedat = endedat;
		this.oerc1Hund = oerc1Hund;
		this.oerc2Hund = oerc2Hund;
		this.noerc1Hund = noerc1Hund;
		this.noerc2Hund = noerc2Hund;
	}

	public int getIdkurs() {
		return this.idkurs;
	}

	public void setIdkurs(int idkurs) {
		this.idkurs = idkurs;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getKursbezeichnung() {
		return this.kursbezeichnung;
	}

	public void setKursbezeichnung(String kursbezeichnung) {
		this.kursbezeichnung = kursbezeichnung;
	}

	public Date getStartdat() {
		return this.startdat;
	}

	public void setStartdat(Date startdat) {
		this.startdat = startdat;
	}

	public Date getEndedat() {
		return this.endedat;
	}

	public void setEndedat(Date endedat) {
		this.endedat = endedat;
	}

	public BigDecimal getOerc1Hund() {
		return this.oerc1Hund;
	}

	public void setOerc1Hund(BigDecimal oerc1Hund) {
		this.oerc1Hund = oerc1Hund;
	}

	public BigDecimal getOerc2Hund() {
		return this.oerc2Hund;
	}

	public void setOerc2Hund(BigDecimal oerc2Hund) {
		this.oerc2Hund = oerc2Hund;
	}

	public BigDecimal getNoerc1Hund() {
		return this.noerc1Hund;
	}

	public void setNoerc1Hund(BigDecimal noerc1Hund) {
		this.noerc1Hund = noerc1Hund;
	}

	public BigDecimal getNoerc2Hund() {
		return this.noerc2Hund;
	}

	public void setNoerc2Hund(BigDecimal noerc2Hund) {
		this.noerc2Hund = noerc2Hund;
	}

}
