package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * kursteilnehmer generated by hbm2java
 */
public class kursteilnehmer implements java.io.Serializable {

	private int idkursteilnehmer;
	private int version;
	private int idkursstunde;
	private int idhund;
	private String abwfuehrer;
	private char kursbezahlt;

	public kursteilnehmer() {
	}

	public kursteilnehmer(int idkursstunde, int idhund, char kursbezahlt) {
		this.idkursstunde = idkursstunde;
		this.idhund = idhund;
		this.kursbezahlt = kursbezahlt;
	}

	public kursteilnehmer(int idkursstunde, int idhund, String abwfuehrer, char kursbezahlt) {
		this.idkursstunde = idkursstunde;
		this.idhund = idhund;
		this.abwfuehrer = abwfuehrer;
		this.kursbezahlt = kursbezahlt;
	}

	public int getIdkursteilnehmer() {
		return this.idkursteilnehmer;
	}

	public void setIdkursteilnehmer(int idkursteilnehmer) {
		this.idkursteilnehmer = idkursteilnehmer;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getIdkursstunde() {
		return this.idkursstunde;
	}

	public void setIdkursstunde(int idkursstunde) {
		this.idkursstunde = idkursstunde;
	}

	public int getIdhund() {
		return this.idhund;
	}

	public void setIdhund(int idhund) {
		this.idhund = idhund;
	}

	public String getAbwfuehrer() {
		return this.abwfuehrer;
	}

	public void setAbwfuehrer(String abwfuehrer) {
		this.abwfuehrer = abwfuehrer;
	}

	public char getKursbezahlt() {
		return this.kursbezahlt;
	}

	public void setKursbezahlt(char kursbezahlt) {
		this.kursbezahlt = kursbezahlt;
	}

}
