package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * oerc_hund_neu generated by hbm2java
 */
public class oerc_hund_neu implements java.io.Serializable {

	private int oercId;
	private String name;
	private String wurfDatum;
	private String rasse;
	private String geschlecht;
	private String vater;
	private String mutter;
	private String chipnummer;
	private String zuchtbuch;
	private String zuchtbuchnummer;

	public oerc_hund_neu() {
	}

	public oerc_hund_neu(int oercId, String name, String rasse, String geschlecht, String zuchtbuch,
			String zuchtbuchnummer) {
		this.oercId = oercId;
		this.name = name;
		this.rasse = rasse;
		this.geschlecht = geschlecht;
		this.zuchtbuch = zuchtbuch;
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

	public oerc_hund_neu(int oercId, String name, String wurfDatum, String rasse, String geschlecht, String vater,
			String mutter, String chipnummer, String zuchtbuch, String zuchtbuchnummer) {
		this.oercId = oercId;
		this.name = name;
		this.wurfDatum = wurfDatum;
		this.rasse = rasse;
		this.geschlecht = geschlecht;
		this.vater = vater;
		this.mutter = mutter;
		this.chipnummer = chipnummer;
		this.zuchtbuch = zuchtbuch;
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

	public int getOercId() {
		return this.oercId;
	}

	public void setOercId(int oercId) {
		this.oercId = oercId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWurfDatum() {
		return this.wurfDatum;
	}

	public void setWurfDatum(String wurfDatum) {
		this.wurfDatum = wurfDatum;
	}

	public String getRasse() {
		return this.rasse;
	}

	public void setRasse(String rasse) {
		this.rasse = rasse;
	}

	public String getGeschlecht() {
		return this.geschlecht;
	}

	public void setGeschlecht(String geschlecht) {
		this.geschlecht = geschlecht;
	}

	public String getVater() {
		return this.vater;
	}

	public void setVater(String vater) {
		this.vater = vater;
	}

	public String getMutter() {
		return this.mutter;
	}

	public void setMutter(String mutter) {
		this.mutter = mutter;
	}

	public String getChipnummer() {
		return this.chipnummer;
	}

	public void setChipnummer(String chipnummer) {
		this.chipnummer = chipnummer;
	}

	public String getZuchtbuch() {
		return this.zuchtbuch;
	}

	public void setZuchtbuch(String zuchtbuch) {
		this.zuchtbuch = zuchtbuch;
	}

	public String getZuchtbuchnummer() {
		return this.zuchtbuchnummer;
	}

	public void setZuchtbuchnummer(String zuchtbuchnummer) {
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

}
