package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * schauhund generated by hbm2java
 */
public class schauhund implements java.io.Serializable {

	private int idschauhund;
	private int version;
	private int idschauring;
	private String name;
	private Date wurftag;
	private String zuchtbuchnummer;
	private String chipnummer;
	private String katalognummer;
	private String klasse;
	private String rasse;
	private String vater;
	private String mutter;
	private String besitzershow;
	private String bewertung;
	private Character hundfehlt;
	private String formwert;
	private Character platzierung;
	private Character caca;
	private Character cacib;
	private Character bob;
	private Character clubsieger;
	private Character bestehrenring;
	private Character platzehrenring;
	private Character platzehrenringgruppe;
	private Character bod;
	private Character bis;
	private Integer oercid;
	private int idschau;
	private char geschlecht;
	private String zuechter;
	private BigDecimal sortKatNr;
	private Integer idTeilnehmer;
	private char mitglied;

	public schauhund() {
	}

	public schauhund(int idschauring, String name, Date wurftag, String zuchtbuchnummer, String chipnummer,
			String katalognummer, String klasse, String rasse, String vater, String mutter, String besitzershow,
			int idschau, char geschlecht, BigDecimal sortKatNr, char mitglied) {
		this.idschauring = idschauring;
		this.name = name;
		this.wurftag = wurftag;
		this.zuchtbuchnummer = zuchtbuchnummer;
		this.chipnummer = chipnummer;
		this.katalognummer = katalognummer;
		this.klasse = klasse;
		this.rasse = rasse;
		this.vater = vater;
		this.mutter = mutter;
		this.besitzershow = besitzershow;
		this.idschau = idschau;
		this.geschlecht = geschlecht;
		this.sortKatNr = sortKatNr;
		this.mitglied = mitglied;
	}

	public schauhund(int idschauring, String name, Date wurftag, String zuchtbuchnummer, String chipnummer,
			String katalognummer, String klasse, String rasse, String vater, String mutter, String besitzershow,
			String bewertung, Character hundfehlt, String formwert, Character platzierung, Character caca,
			Character cacib, Character bob, Character clubsieger, Character bestehrenring, Character platzehrenring,
			Character platzehrenringgruppe, Character bod, Character bis, Integer oercid, int idschau, char geschlecht,
			String zuechter, BigDecimal sortKatNr, Integer idTeilnehmer, char mitglied) {
		this.idschauring = idschauring;
		this.name = name;
		this.wurftag = wurftag;
		this.zuchtbuchnummer = zuchtbuchnummer;
		this.chipnummer = chipnummer;
		this.katalognummer = katalognummer;
		this.klasse = klasse;
		this.rasse = rasse;
		this.vater = vater;
		this.mutter = mutter;
		this.besitzershow = besitzershow;
		this.bewertung = bewertung;
		this.hundfehlt = hundfehlt;
		this.formwert = formwert;
		this.platzierung = platzierung;
		this.caca = caca;
		this.cacib = cacib;
		this.bob = bob;
		this.clubsieger = clubsieger;
		this.bestehrenring = bestehrenring;
		this.platzehrenring = platzehrenring;
		this.platzehrenringgruppe = platzehrenringgruppe;
		this.bod = bod;
		this.bis = bis;
		this.oercid = oercid;
		this.idschau = idschau;
		this.geschlecht = geschlecht;
		this.zuechter = zuechter;
		this.sortKatNr = sortKatNr;
		this.idTeilnehmer = idTeilnehmer;
		this.mitglied = mitglied;
	}

	public int getIdschauhund() {
		return this.idschauhund;
	}

	public void setIdschauhund(int idschauhund) {
		this.idschauhund = idschauhund;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getIdschauring() {
		return this.idschauring;
	}

	public void setIdschauring(int idschauring) {
		this.idschauring = idschauring;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getWurftag() {
		return this.wurftag;
	}

	public void setWurftag(Date wurftag) {
		this.wurftag = wurftag;
	}

	public String getZuchtbuchnummer() {
		return this.zuchtbuchnummer;
	}

	public void setZuchtbuchnummer(String zuchtbuchnummer) {
		this.zuchtbuchnummer = zuchtbuchnummer;
	}

	public String getChipnummer() {
		return this.chipnummer;
	}

	public void setChipnummer(String chipnummer) {
		this.chipnummer = chipnummer;
	}

	public String getKatalognummer() {
		return this.katalognummer;
	}

	public void setKatalognummer(String katalognummer) {
		this.katalognummer = katalognummer;
	}

	public String getKlasse() {
		return this.klasse;
	}

	public void setKlasse(String klasse) {
		this.klasse = klasse;
	}

	public String getRasse() {
		return this.rasse;
	}

	public void setRasse(String rasse) {
		this.rasse = rasse;
	}

	public String getVater() {
		return this.vater;
	}

	public void setVater(String vater) {
		this.vater = vater;
	}

	public String getMutter() {
		return this.mutter;
	}

	public void setMutter(String mutter) {
		this.mutter = mutter;
	}

	public String getBesitzershow() {
		return this.besitzershow;
	}

	public void setBesitzershow(String besitzershow) {
		this.besitzershow = besitzershow;
	}

	public String getBewertung() {
		return this.bewertung;
	}

	public void setBewertung(String bewertung) {
		this.bewertung = bewertung;
	}

	public Character getHundfehlt() {
		return this.hundfehlt;
	}

	public void setHundfehlt(Character hundfehlt) {
		this.hundfehlt = hundfehlt;
	}

	public String getFormwert() {
		return this.formwert;
	}

	public void setFormwert(String formwert) {
		this.formwert = formwert;
	}

	public Character getPlatzierung() {
		return this.platzierung;
	}

	public void setPlatzierung(Character platzierung) {
		this.platzierung = platzierung;
	}

	public Character getCaca() {
		return this.caca;
	}

	public void setCaca(Character caca) {
		this.caca = caca;
	}

	public Character getCacib() {
		return this.cacib;
	}

	public void setCacib(Character cacib) {
		this.cacib = cacib;
	}

	public Character getBob() {
		return this.bob;
	}

	public void setBob(Character bob) {
		this.bob = bob;
	}

	public Character getClubsieger() {
		return this.clubsieger;
	}

	public void setClubsieger(Character clubsieger) {
		this.clubsieger = clubsieger;
	}

	public Character getBestehrenring() {
		return this.bestehrenring;
	}

	public void setBestehrenring(Character bestehrenring) {
		this.bestehrenring = bestehrenring;
	}

	public Character getPlatzehrenring() {
		return this.platzehrenring;
	}

	public void setPlatzehrenring(Character platzehrenring) {
		this.platzehrenring = platzehrenring;
	}

	public Character getPlatzehrenringgruppe() {
		return this.platzehrenringgruppe;
	}

	public void setPlatzehrenringgruppe(Character platzehrenringgruppe) {
		this.platzehrenringgruppe = platzehrenringgruppe;
	}

	public Character getBod() {
		return this.bod;
	}

	public void setBod(Character bod) {
		this.bod = bod;
	}

	public Character getBis() {
		return this.bis;
	}

	public void setBis(Character bis) {
		this.bis = bis;
	}

	public Integer getOercid() {
		return this.oercid;
	}

	public void setOercid(Integer oercid) {
		this.oercid = oercid;
	}

	public int getIdschau() {
		return this.idschau;
	}

	public void setIdschau(int idschau) {
		this.idschau = idschau;
	}

	public char getGeschlecht() {
		return this.geschlecht;
	}

	public void setGeschlecht(char geschlecht) {
		this.geschlecht = geschlecht;
	}

	public String getZuechter() {
		return this.zuechter;
	}

	public void setZuechter(String zuechter) {
		this.zuechter = zuechter;
	}

	public BigDecimal getSortKatNr() {
		return this.sortKatNr;
	}

	public void setSortKatNr(BigDecimal sortKatNr) {
		this.sortKatNr = sortKatNr;
	}

	public Integer getIdTeilnehmer() {
		return this.idTeilnehmer;
	}

	public void setIdTeilnehmer(Integer idTeilnehmer) {
		this.idTeilnehmer = idTeilnehmer;
	}

	public char getMitglied() {
		return this.mitglied;
	}

	public void setMitglied(char mitglied) {
		this.mitglied = mitglied;
	}

}
