package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * schau generated by hbm2java
 */
public class schau implements java.io.Serializable {

	private int idschau;
	private int version;
	private String bezeichnung;
	private char schautyp;
	private Date datum;
	private String leiter;
	private String schaukuerzel;
	private Integer idVeranstaltung;

	public schau() {
	}

	public schau(String bezeichnung, char schautyp, Date datum, String schaukuerzel) {
		this.bezeichnung = bezeichnung;
		this.schautyp = schautyp;
		this.datum = datum;
		this.schaukuerzel = schaukuerzel;
	}

	public schau(String bezeichnung, char schautyp, Date datum, String leiter, String schaukuerzel,
			Integer idVeranstaltung) {
		this.bezeichnung = bezeichnung;
		this.schautyp = schautyp;
		this.datum = datum;
		this.leiter = leiter;
		this.schaukuerzel = schaukuerzel;
		this.idVeranstaltung = idVeranstaltung;
	}

	public int getIdschau() {
		return this.idschau;
	}

	public void setIdschau(int idschau) {
		this.idschau = idschau;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public char getSchautyp() {
		return this.schautyp;
	}

	public void setSchautyp(char schautyp) {
		this.schautyp = schautyp;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getLeiter() {
		return this.leiter;
	}

	public void setLeiter(String leiter) {
		this.leiter = leiter;
	}

	public String getSchaukuerzel() {
		return this.schaukuerzel;
	}

	public void setSchaukuerzel(String schaukuerzel) {
		this.schaukuerzel = schaukuerzel;
	}

	public Integer getIdVeranstaltung() {
		return this.idVeranstaltung;
	}

	public void setIdVeranstaltung(Integer idVeranstaltung) {
		this.idVeranstaltung = idVeranstaltung;
	}

}
