package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * schauring generated by hbm2java
 */
public class schauring implements java.io.Serializable {

	private int idschauring;
	private int version;
	private int idschau;
	private String richter;
	private String ringnummer;

	public schauring() {
	}

	public schauring(int idschau, String richter, String ringnummer) {
		this.idschau = idschau;
		this.richter = richter;
		this.ringnummer = ringnummer;
	}

	public int getIdschauring() {
		return this.idschauring;
	}

	public void setIdschauring(int idschauring) {
		this.idschauring = idschauring;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getIdschau() {
		return this.idschau;
	}

	public void setIdschau(int idschau) {
		this.idschau = idschau;
	}

	public String getRichter() {
		return this.richter;
	}

	public void setRichter(String richter) {
		this.richter = richter;
	}

	public String getRingnummer() {
		return this.ringnummer;
	}

	public void setRingnummer(String ringnummer) {
		this.ringnummer = ringnummer;
	}

}
