package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * user generated by hbm2java
 */
public class user implements java.io.Serializable {

	private int iduser;
	private int version;
	private String email;
	private Date letzteAenderung;
	private String rollen;
	private byte[] pass;

	public user() {
	}

	public user(int iduser, String email, Date letzteAenderung, String rollen, byte[] pass) {
		this.iduser = iduser;
		this.email = email;
		this.letzteAenderung = letzteAenderung;
		this.rollen = rollen;
		this.pass = pass;
	}

	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung = letzteAenderung;
	}

	public String getRollen() {
		return this.rollen;
	}

	public void setRollen(String rollen) {
		this.rollen = rollen;
	}

	public byte[] getPass() {
		return this.pass;
	}

	public void setPass(byte[] pass) {
		this.pass = pass;
	}

}
