package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * veranstaltungs_richter generated by hbm2java
 */
public class veranstaltungs_richter implements java.io.Serializable {

	private int idRichter;
	private int idVeranstaltung;
	private int lfdNr;
	private String richterName;

	public veranstaltungs_richter() {
	}

	public veranstaltungs_richter(int idRichter, int idVeranstaltung, int lfdNr, String richterName) {
		this.idRichter = idRichter;
		this.idVeranstaltung = idVeranstaltung;
		this.lfdNr = lfdNr;
		this.richterName = richterName;
	}

	public int getIdRichter() {
		return this.idRichter;
	}

	public void setIdRichter(int idRichter) {
		this.idRichter = idRichter;
	}

	public int getIdVeranstaltung() {
		return this.idVeranstaltung;
	}

	public void setIdVeranstaltung(int idVeranstaltung) {
		this.idVeranstaltung = idVeranstaltung;
	}

	public int getLfdNr() {
		return this.lfdNr;
	}

	public void setLfdNr(int lfdNr) {
		this.lfdNr = lfdNr;
	}

	public String getRichterName() {
		return this.richterName;
	}

	public void setRichterName(String richterName) {
		this.richterName = richterName;
	}

}
