package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

/**
 * veranstaltungs_teilnehmer generated by hbm2java
 */
public class veranstaltungs_teilnehmer implements java.io.Serializable {

	private int idTeilnehmer;
	private int version;
	private int idVeranstaltung;
	private int idStufe;
	private int idHund;
	private int idPerson;
	private char bezahlt;
	private Character bestanden;
	private Integer gesPunkte;
	private String hundefuehrer;
	private Integer uebung1;
	private Integer uebung2;
	private Integer uebung3;
	private Integer uebung4;
	private Integer uebung5;
	private Integer uebung6;
	private Integer uebung7;
	private Integer uebung8;
	private Character sonderwertung;
	private String bemerkung;
	private Integer gruppe;
	private Character formwert;
	private int platzierung;
	private int startnr;

	public veranstaltungs_teilnehmer() {
	}

	public veranstaltungs_teilnehmer(int idVeranstaltung, int idStufe, int idHund, int idPerson, char bezahlt,
			int platzierung, int startnr) {
		this.idVeranstaltung = idVeranstaltung;
		this.idStufe = idStufe;
		this.idHund = idHund;
		this.idPerson = idPerson;
		this.bezahlt = bezahlt;
		this.platzierung = platzierung;
		this.startnr = startnr;
	}

	public veranstaltungs_teilnehmer(int idVeranstaltung, int idStufe, int idHund, int idPerson, char bezahlt,
			Character bestanden, Integer gesPunkte, String hundefuehrer, Integer uebung1, Integer uebung2,
			Integer uebung3, Integer uebung4, Integer uebung5, Integer uebung6, Integer uebung7, Integer uebung8,
			Character sonderwertung, String bemerkung, Integer gruppe, Character formwert, int platzierung,
			int startnr) {
		this.idVeranstaltung = idVeranstaltung;
		this.idStufe = idStufe;
		this.idHund = idHund;
		this.idPerson = idPerson;
		this.bezahlt = bezahlt;
		this.bestanden = bestanden;
		this.gesPunkte = gesPunkte;
		this.hundefuehrer = hundefuehrer;
		this.uebung1 = uebung1;
		this.uebung2 = uebung2;
		this.uebung3 = uebung3;
		this.uebung4 = uebung4;
		this.uebung5 = uebung5;
		this.uebung6 = uebung6;
		this.uebung7 = uebung7;
		this.uebung8 = uebung8;
		this.sonderwertung = sonderwertung;
		this.bemerkung = bemerkung;
		this.gruppe = gruppe;
		this.formwert = formwert;
		this.platzierung = platzierung;
		this.startnr = startnr;
	}

	public int getIdTeilnehmer() {
		return this.idTeilnehmer;
	}

	public void setIdTeilnehmer(int idTeilnehmer) {
		this.idTeilnehmer = idTeilnehmer;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getIdVeranstaltung() {
		return this.idVeranstaltung;
	}

	public void setIdVeranstaltung(int idVeranstaltung) {
		this.idVeranstaltung = idVeranstaltung;
	}

	public int getIdStufe() {
		return this.idStufe;
	}

	public void setIdStufe(int idStufe) {
		this.idStufe = idStufe;
	}

	public int getIdHund() {
		return this.idHund;
	}

	public void setIdHund(int idHund) {
		this.idHund = idHund;
	}

	public int getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(int idPerson) {
		this.idPerson = idPerson;
	}

	public char getBezahlt() {
		return this.bezahlt;
	}

	public void setBezahlt(char bezahlt) {
		this.bezahlt = bezahlt;
	}

	public Character getBestanden() {
		return this.bestanden;
	}

	public void setBestanden(Character bestanden) {
		this.bestanden = bestanden;
	}

	public Integer getGesPunkte() {
		return this.gesPunkte;
	}

	public void setGesPunkte(Integer gesPunkte) {
		this.gesPunkte = gesPunkte;
	}

	public String getHundefuehrer() {
		return this.hundefuehrer;
	}

	public void setHundefuehrer(String hundefuehrer) {
		this.hundefuehrer = hundefuehrer;
	}

	public Integer getUebung1() {
		return this.uebung1;
	}

	public void setUebung1(Integer uebung1) {
		this.uebung1 = uebung1;
	}

	public Integer getUebung2() {
		return this.uebung2;
	}

	public void setUebung2(Integer uebung2) {
		this.uebung2 = uebung2;
	}

	public Integer getUebung3() {
		return this.uebung3;
	}

	public void setUebung3(Integer uebung3) {
		this.uebung3 = uebung3;
	}

	public Integer getUebung4() {
		return this.uebung4;
	}

	public void setUebung4(Integer uebung4) {
		this.uebung4 = uebung4;
	}

	public Integer getUebung5() {
		return this.uebung5;
	}

	public void setUebung5(Integer uebung5) {
		this.uebung5 = uebung5;
	}

	public Integer getUebung6() {
		return this.uebung6;
	}

	public void setUebung6(Integer uebung6) {
		this.uebung6 = uebung6;
	}

	public Integer getUebung7() {
		return this.uebung7;
	}

	public void setUebung7(Integer uebung7) {
		this.uebung7 = uebung7;
	}

	public Integer getUebung8() {
		return this.uebung8;
	}

	public void setUebung8(Integer uebung8) {
		this.uebung8 = uebung8;
	}

	public Character getSonderwertung() {
		return this.sonderwertung;
	}

	public void setSonderwertung(Character sonderwertung) {
		this.sonderwertung = sonderwertung;
	}

	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	public Integer getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(Integer gruppe) {
		this.gruppe = gruppe;
	}

	public Character getFormwert() {
		return this.formwert;
	}

	public void setFormwert(Character formwert) {
		this.formwert = formwert;
	}

	public int getPlatzierung() {
		return this.platzierung;
	}

	public void setPlatzierung(int platzierung) {
		this.platzierung = platzierung;
	}

	public int getStartnr() {
		return this.startnr;
	}

	public void setStartnr(int startnr) {
		this.startnr = startnr;
	}

}
