package com.app.entitites;

// default package
// Generated 30.09.2019 14:19:33 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * veranstaltung generated by hbm2java
 */
public class veranstaltung implements java.io.Serializable {

	private int idVeranstaltung;
	private int version;
	private String name;
	private Date datum;
	private String richter;
	private String veranstaltungsleiter;
	private int typ;
	private String veranstalter;
	private String veranstaltungsort;
	private String plzLeiter;
	private String ortLeiter;
	private String strasseLeiter;
	private String telNrLeiter;
	private Integer idschau;

	public veranstaltung() {
	}

	public veranstaltung(String name, Date datum, String richter, String veranstaltungsleiter, int typ) {
		this.name = name;
		this.datum = datum;
		this.richter = richter;
		this.veranstaltungsleiter = veranstaltungsleiter;
		this.typ = typ;
	}

	public veranstaltung(String name, Date datum, String richter, String veranstaltungsleiter, int typ,
			String veranstalter, String veranstaltungsort, String plzLeiter, String ortLeiter, String strasseLeiter,
			String telNrLeiter, Integer idschau) {
		this.name = name;
		this.datum = datum;
		this.richter = richter;
		this.veranstaltungsleiter = veranstaltungsleiter;
		this.typ = typ;
		this.veranstalter = veranstalter;
		this.veranstaltungsort = veranstaltungsort;
		this.plzLeiter = plzLeiter;
		this.ortLeiter = ortLeiter;
		this.strasseLeiter = strasseLeiter;
		this.telNrLeiter = telNrLeiter;
		this.idschau = idschau;
	}

	public int getIdVeranstaltung() {
		return this.idVeranstaltung;
	}

	public void setIdVeranstaltung(int idVeranstaltung) {
		this.idVeranstaltung = idVeranstaltung;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public String getRichter() {
		return this.richter;
	}

	public void setRichter(String richter) {
		this.richter = richter;
	}

	public String getVeranstaltungsleiter() {
		return this.veranstaltungsleiter;
	}

	public void setVeranstaltungsleiter(String veranstaltungsleiter) {
		this.veranstaltungsleiter = veranstaltungsleiter;
	}

	public int getTyp() {
		return this.typ;
	}

	public void setTyp(int typ) {
		this.typ = typ;
	}

	public String getVeranstalter() {
		return this.veranstalter;
	}

	public void setVeranstalter(String veranstalter) {
		this.veranstalter = veranstalter;
	}

	public String getVeranstaltungsort() {
		return this.veranstaltungsort;
	}

	public void setVeranstaltungsort(String veranstaltungsort) {
		this.veranstaltungsort = veranstaltungsort;
	}

	public String getPlzLeiter() {
		return this.plzLeiter;
	}

	public void setPlzLeiter(String plzLeiter) {
		this.plzLeiter = plzLeiter;
	}

	public String getOrtLeiter() {
		return this.ortLeiter;
	}

	public void setOrtLeiter(String ortLeiter) {
		this.ortLeiter = ortLeiter;
	}

	public String getStrasseLeiter() {
		return this.strasseLeiter;
	}

	public void setStrasseLeiter(String strasseLeiter) {
		this.strasseLeiter = strasseLeiter;
	}

	public String getTelNrLeiter() {
		return this.telNrLeiter;
	}

	public void setTelNrLeiter(String telNrLeiter) {
		this.telNrLeiter = telNrLeiter;
	}

	public Integer getIdschau() {
		return this.idschau;
	}

	public void setIdschau(Integer idschau) {
		this.idschau = idschau;
	}

}
