package com.example.testUIWithLogin;

import java.util.Locale;

import org.springframework.context.ApplicationContext;

import com.app.bean.LandBean;
import com.app.enumPackage.LandEnum;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractSelect.ItemCaptionMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

public class RegisterForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button abbrechen;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private ComboBox Land;
	@AutoGenerated
	private PopupDateField gebdat;
	@AutoGenerated
	private TextField email;
	@AutoGenerated 
	private TextField hausnummer;
	@AutoGenerated
	private TextField Ort;
	@AutoGenerated
	private TextField PLZ;
	@AutoGenerated
	private TextField Strasse;
	@AutoGenerated
	private TextField Nachname;
	@AutoGenerated
	private TextField Vorname;
	@AutoGenerated
	private Button Registrieren;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RegisterForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		RegisterPersonFormListener listener = getRegisterPersonFormListener();
		this.abbrechen.setId("abbrechen");
		this.abbrechen.addClickListener(listener);
		this.Registrieren.setId("registrieren");
		this.Registrieren.addClickListener(listener);
		this.gebdat.setResolution(Resolution.DAY);
		this.gebdat.setLocale(new Locale("de","DE"));
		
		BeanItemContainer<LandBean> container =
			        new BeanItemContainer<LandBean>(LandBean.class);

		for(LandEnum o : LandEnum.values()) {
			container.addItem(new LandBean(o.getLandKurzBezeichnung(),o.getLandLangBezeichnung()));
			
		}
		
		this.Land.setContainerDataSource(container);
		this.Land.setItemCaptionMode(ItemCaptionMode.PROPERTY);
		this.Land.setItemCaptionPropertyId("landLangBezeichnung");


	}
	
	 public RegisterPersonFormListener getRegisterPersonFormListener() {
	    	testUIWithLogin ui = (testUIWithLogin) UI.getCurrent();
	        ApplicationContext context = ui.getApplicationContext();
	        return context.getBean(RegisterPersonFormListener.class);
	 }

	public AbsoluteLayout getMainLayout() {
		return mainLayout;
	}

	public GridLayout getGridLayout_1() {
		return gridLayout_1;
	}

	public HorizontalLayout getHorizontalLayout_1() {
		return horizontalLayout_1;
	}

	public Button getAbbrechen() {
		return abbrechen;
	}

	public VerticalLayout getVerticalLayout_1() {
		return verticalLayout_1;
	}

	public TextField getEmail() {
		return email;
	}

	public TextField getOrt() {
		return Ort;
	}

	public TextField getStrasse() {
		return Strasse;
	}

	public TextField getNachname() {
		return Nachname;
	}

	public TextField getVorname() {
		return Vorname;
	}

	public Button getRegistrieren() {
		return Registrieren;
	}

	public TextField getHausnummer() {
		return hausnummer;
	}

	public PopupDateField getGebdat() {
		return gebdat;
	}

	public ComboBox getLand() {
		return Land;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("760px");
		gridLayout_1.setHeight("660px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(3);
		gridLayout_1.setRows(3);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		gridLayout_1.addComponent(horizontalLayout_1, 1, 1);
		gridLayout_1.setComponentAlignment(horizontalLayout_1,
				new Alignment(48));
		
		return gridLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("396px");
		horizontalLayout_1.setHeight("579px");
		horizontalLayout_1.setMargin(false);
		
		// Registrieren
		Registrieren = new Button();
		Registrieren.setCaption("Registrieren");
		Registrieren.setImmediate(true);
		Registrieren.setWidth("-1px");
		Registrieren.setHeight("-1px");
		horizontalLayout_1.addComponent(Registrieren);
		horizontalLayout_1
				.setComponentAlignment(Registrieren, new Alignment(9));
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		horizontalLayout_1.addComponent(verticalLayout_1);
		horizontalLayout_1.setComponentAlignment(verticalLayout_1,
				new Alignment(48));
		
		// abbrechen
		abbrechen = new Button();
		abbrechen.setCaption("Abbrechen");
		abbrechen.setImmediate(true);
		abbrechen.setDescription("Abbrechen");
		abbrechen.setWidth("-1px");
		abbrechen.setHeight("-1px");
		horizontalLayout_1.addComponent(abbrechen);
		horizontalLayout_1.setComponentAlignment(abbrechen, new Alignment(10));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("136px");
		verticalLayout_1.setHeight("379px");
		verticalLayout_1.setMargin(false);
		
		// Vorname
		Vorname = new TextField();
		Vorname.setImmediate(false);
		Vorname.setWidth("-1px");
		Vorname.setHeight("-1px");
		Vorname.setInputPrompt("Vorname");
		Vorname.setMaxLength(45);
		verticalLayout_1.addComponent(Vorname);
		
		// Nachname
		Nachname = new TextField();
		Nachname.setImmediate(false);
		Nachname.setWidth("-1px");
		Nachname.setHeight("-1px");
		Nachname.setInputPrompt("Nachname");
		Nachname.setMaxLength(45);
		verticalLayout_1.addComponent(Nachname);
		
		// Strasse
		Strasse = new TextField();
		Strasse.setImmediate(false);
		Strasse.setWidth("-1px");
		Strasse.setHeight("-1px");
		Strasse.setInputPrompt("Strasse");
		Strasse.setMaxLength(45);
		verticalLayout_1.addComponent(Strasse);
		
		// PLZ
		PLZ = new TextField();
		PLZ.setImmediate(false);
		PLZ.setDescription("PLZ");
		PLZ.setWidth("-1px");
		PLZ.setHeight("-1px");
		PLZ.setInputPrompt("PLZ");
		verticalLayout_1.addComponent(PLZ);
		
		// Ort
		Ort = new TextField();
		Ort.setImmediate(false);
		Ort.setWidth("-1px");
		Ort.setHeight("-1px");
		Ort.setInputPrompt("Ort");
		Ort.setMaxLength(45);
		verticalLayout_1.addComponent(Ort);
		
		// hausnummer
		hausnummer = new TextField();
		hausnummer.setImmediate(false);
		hausnummer.setWidth("-1px");
		hausnummer.setHeight("-1px");
		hausnummer.setInputPrompt("Hausnummer");
		hausnummer.setMaxLength(10);
		verticalLayout_1.addComponent(hausnummer);
		
		// email
		email = new TextField();
		email.setImmediate(false);
		email.setWidth("-1px");
		email.setHeight("-1px");
		email.setInputPrompt("email");
		verticalLayout_1.addComponent(email);
		
		// gebdat
		gebdat = new PopupDateField();
		gebdat.setImmediate(false);
		gebdat.setWidth("136px");
		gebdat.setHeight("-1px");
		verticalLayout_1.addComponent(gebdat);
		
		// Land
		Land = new ComboBox();
		Land.setImmediate(false);
		Land.setDescription("Land");
		Land.setWidth("-1px");
		Land.setHeight("-1px");
		Land.setRequired(true);
		verticalLayout_1.addComponent(Land);
		
		return verticalLayout_1;
	}

	public TextField getPLZ() {
		return PLZ;
	}
 
	
}
